#!/usr/bin/env bash
# Scaffold a new feature folder under .ai/artifacts/features/<slug>/
# Installed into <project>/.ai/scripts/new-feature.sh by the relay-setup skill.
# Usage: .ai/scripts/new-feature.sh <slug>
set -euo pipefail

SLUG="${1:?Usage: $0 <slug>}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FEATURE_DIR="$ROOT/.ai/artifacts/features/$SLUG"

if [ -d "$FEATURE_DIR" ]; then
  echo "  Feature folder already exists: $FEATURE_DIR"
  exit 0
fi

mkdir -p "$FEATURE_DIR"

cat > "$FEATURE_DIR/feature-brief.md" <<EOF
# Feature brief

**Feature slug:** $SLUG
**Status:** Draft

_This file is generated by the PM agent. Run \`agent-runner.ts --role=pm --slug=$SLUG\` to populate it._
EOF

echo "  Scaffolded feature folder: $FEATURE_DIR"
